#!/bin/bash
#
# Notes:
#   On Mac OS X VTK does not compile out of the box with self-compiled GCC.
#   grep vor "long-branch" and "pascal-string" in the cmake configuration
#   and remove these strings.
#

source "$(dirname $0)/../../../lib/libpmodules.bash"

case ${OS} in
Darwin )
	pmodules.pre_configure() {
		# for the time being: on Mac OS X we need GL/gl.h from MacPorts:
		std::append_path C_INLCUDE_PATH '/opt/local/include'
		std::append_path CPLUS_INCLUDE_PATH '/opt/local/include'
	}
	;;
esac

pmodules.configure() {
	cmake -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
		-DVTK_INSTALL_INCLUDE_DIR:PATH=include \
		-DVTK_INSTALL_LIB_DIR:PATH=lib \
		-DVTK_USE_COCOA:BOOL=OFF \
		"${MODULE_SRCDIR}"
}

pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies 'cmake' "${COMPILER}"
pmodules.make_all

