format: 1
shs-cassini-headers:
  defaults:
    group: Libraries
    compile_in_sourcetree: true
    relstage: unstable
    urls:
      - url: https://github.com/HewlettPackard/shs-cassini-headers/archive/refs/tags/release/shs-${V_PKG}.tar.gz
        name: shs-cassini-headers-${V_PKG}.tar.bz2
  shasums:
    shs-cassini-headers-13.0.0.tar.bz2: 69152b3e2a827812e1cd38deb12a0c7ed37d99ea914850ce23b0e38b2588c50d
    shs-cassini-headers-12.0.1.tar.bz2: db338e6af8bff8c5acd0556bbad81eba5365db9eec918d46021483861a386792
  versions:
    13.1.0:
      config:
        relstage: unstable
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          suffix: '-oss'
          use_overlays: [PSI]
          use_flags: [merlin7]
    13.0.0:
      config:
        relstage: unstable
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          suffix: '-oss'
          use_overlays: [PSI]
          use_flags: [merlin7]
    12.0.1:
      config:
        relstage: stable
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          suffix: '-oss'
          use_overlays: [PSI]
          use_flags: [merlin7]
