#!/bin/bash

P='OPAL'

source "$(dirname $0)/../../../lib/libpmodules.bash"


module use unstable

# add -fopenmp to CC and CXX, if you want to compile with OpenMP
pmodules.configure() {
	cmake \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		-DCMAKE_BUILD_TYPE=RELEASE \
		-DENABLE_SAAMG_SOLVER=TRUE \
		"${MODULE_SRCDIR}"
}

pmodules.add_to_group 'MPI'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}"
pmodules.set_build_dependencies 'cmake' "${COMPILER}" "${MPI}" 'boost' 'hdf5' 'H5hut' 'trilinos' 'gsl'
pmodules.set_supported_compilers 'gcc/4.7' 'gcc/4.8'
pmodules.make_all

