---
# yamllint disable rule:line-length
format: 1
lapack:
  defaults:
    group: Compiler
    overlay: base
    relstage: stable
    urls:
      - url: https://github.com/Reference-LAPACK/lapack/archive/refs/tags/v${V_PKG}.tar.gz
        name: lapack-${V_PKG}.tar.gz
    configure_args:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=ON
      - -DLAPACKE=ON
    docfiles:
      - LICENSE
      - README.md
  shasums:
    lapack-3.12.1.tar.gz: 2ca6407a001a474d4d4d35f3a61550156050c48016d949f0da0529c0aa052422

  versions:
    3.12.1:
      variants:
        - systems: [.*.merlin7.psi.ch]
          target_cpus: [x86_64]
          relstage: unstable
          overlay: PSI
          use_overlays: [PSI, Alps]
          group_deps:
            compiler: {gcc: [13.4.0], nvhpc: [26.5_cuda_multi]}
          build_requires: [cmake/4.4.0]
