#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	unset F90
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-cxx \
		--enable-fortran \
		|| exit 1
}


em.add_to_family 'Compiler'
em.set_runtime_dependencies "${COMPILER}"
em.set_build_dependencies "${COMPILER}"
em.set_docfiles 'COPYRIGHT' 'README'
em.make_all
