#!/bin/bash

CPLUS_INCLUDE_PATH="@PREFIX@/include:@ROOT_PREFIX@/include"

declare -r progname=$(basename "$0")

declare -a args=()

if [[ "${progname}" == "roger" ]]; then
	args+=( "--roger" )
fi

"@PREFIX@/bin/H5root.bin" "${args[@]}" "$@"
