---
# yamllint disable rule:line-length
format: 1
scalapack:
  defaults:
    group: Compiler
    overlay: base
    relstage: stable
    systems: [rhel8, rhel9, rhel10]
    docfiles: [ LICENSE, README]
    configure_with: cmake
    configure_args:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_STATIC_LIBS=ON
    urls:
      - url: https://github.com/Reference-ScaLAPACK/scalapack/archive/refs/tags/v${V_PKG}.tar.gz
        name: scalapack-${V_PKG}.tar.gz
  shasums:
    scalapack-2.2.3.tar.gz: 2f5503090e43f9b676db6d09befbc90116851cd34cbe7339364dfdd8f777e414

  versions:
    2.2.3:
      config:
        configure_args+:
          - -DMPI_BASE_DIR=${MPICH_HOME}
          - -DBLAS_LIBRARIES=${LAPACK_LIBRARY_DIR}
          - -DLAPACK_LIBRARIES=${LAPACK_LIBRARY_DIR}
      variants:
        - systems: [login.*.merlin7.psi.ch, cn.*.merlin7.psi.ch]
          relstage: unstable
          overlay: Alps
          use_overlays: [PSI, Alps]
          group_deps:
            compiler: {gcc: [13.4.0]}
            mpi: {mpich: [5.0.1]}
          configure_args+:
            - -DCMAKE_C_COMPILER=${MPICC}
            - -DCMAKE_CXX_COMPILER=${MPICXX}
            - -DCMAKE_Fortran_COMPILER=${MPIFC}
            - -DSCALAPACK_BUILD_TESTS=OFF
          build_requires: [ cmake/3.27.8, mpich/5.0.1, lapack/3.12.1 ]
        - systems: [gpu.*.merlin7.psi.ch]
          relstage: unstable
          overlay: Alps_A100
          target_cpus: ['x86_64'] # GPU A100
          use_overlays: [PSI, Alps, Alps_A100]
          group_deps:
            compiler: {gcc: [13.4.0]}
            mpi: {mpich: [5.0.1]}
          configure_args+:
            - -DCMAKE_C_COMPILER=${MPICC}
            - -DCMAKE_CXX_COMPILER=${MPICXX}
            - -DCMAKE_Fortran_COMPILER=${MPIFC}
            - -DSCALAPACK_BUILD_TESTS=OFF
          build_requires: [ cmake/3.27.8, mpich/5.0.1, lapack/3.12.1 ]
        - systems: [gpu.*.merlin7.psi.ch]
          relstage: unstable
          overlay: Alps_A100
          target_cpus: ['x86_64'] # GPU A100
          use_overlays: [PSI, Alps, Alps_A100]
          group_deps:
            compiler: {nvhpc: [26.5_cuda_multi]}
            mpi: {mpich: [5.0.1]}
          configure_args+:
            - -DCMAKE_C_COMPILER=${CC}
            - -DCMAKE_CXX_COMPILER=${CXX}
            - -DCMAKE_Fortran_COMPILER=${FC}
            - -DSCALAPACK_BUILD_TESTS=OFF
          build_requires: [ cmake/3.27.8, mpich/5.0.1, lapack/3.12.1 ]
