---
format: 1
xmlto:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    docfiles: [ AUTHORS, COPYING, FAQ, NEWS, README, THANKS ]
    urls:
      - url: https://releases.pagure.org/$P/$P-${V_PKG}.tar.bz2
    compile_in_sourcetree: true
    configure_args:
      - XSLTPROC=$_

  shasums:
    xmlto-0.0.28.tar.bz2: 1130df3a7957eb9f6f0d29e4aa1c75732a7dfb6d639be013859b5c7ec5421276

  versions:
    0.0.28:
      config:
        relstage: stable
