#!/bin/bash

source "$(dirname $0)/../../../lib/libem.bash"

function em.configure() {
	:
}

function em.build() {
        cd "${MODULE_SRCDIR}"

	make -j ${JOBS}
}

function em.install() {
        cd "${MODULE_SRCDIR}"
	mkdir -p ${PREFIX}/bin
	install -m 0755 mdtest "${PREFIX}/bin"
}

#em.supported_os 'Linux'
em.add_to_family 'System'
em.set_build_dependencies "${COMPILER}" "${MPI}"
em.make_all
