---
# yamllint disable rule:line-length
format: 1
qe:
  defaults:
    group: MPI
    overlay: base
    relstage: stable
    systems: [rhel7, rhel8, rhel9]
    docfiles: [AUTHORS, LICENSE, NEWS, README]
    configure_with: cmake
    urls:
      - url: https://gitlab.com/QEF/q-e/-/archive/qe-${V_PKG}/q-e-qe-${V_PKG}.tar.bz2
  shasums:
    qe-7.3.1.tar.bz2: 4955e4ca5e47a0faafefc72442155bef02ff94c8b796698ad81d4804a1cf6d88

  versions:
    7.6:
      config:
        configure_args+:
          - -DQE_ENABLE_MPI:BOOL=ON
          - -DQE_ENABLE_OPENMP:BOOL=ON
          - -DQE_ENABLE_HDF5:BOOL=ON
          - -DCMAKE_C_COMPILER:STRING=${MPICC}
          - -DCMAKE_CXX_COMPILER:STRING=${MPICXX}
          - -DCMAKE_Fortran_COMPILER:STRING=${MPIFC}
          - -DCMAKE_SYSTEM_PROCESSOR=x86_64
        # We disable deprecated pbuild::pre_configure in the build file
        build_functions:
          configure: [pbuild::configure, pbuild::post_configure]
      variants:
        - systems: [login.*.merlin7.psi.ch, cn.*.merlin7.psi.ch]
          relstage: unstable
          overlay: Alps
          use_overlays: [PSI, Alps]
          group_deps:
            compiler: { gcc: [13.4.0] }
            mpi: { openmpi: [5.0.10], mpich: [5.0.1] }
          docfiles: [README.md, README_GPU.md, CONTRIBUTING.md]
          build_requires: [ cmake/4.4.0, git/2.54.0, OpenBLAS/0.3.30, hdf5/2.2.0, fftw/3.3.10 ]
          runtime_deps: [hdf5/2.2.0]
 
        - systems: [gpu1.*.merlin7.psi.ch]
          relstage: unstable
          overlay: Alps_A100
          target_cpus: ['x86_64'] # GPU A100
          use_overlays: [PSI, Alps, Alps_A100]
          group_deps:
            compiler: { nvhpc: [26.5_cuda_multi] }
            mpi: { mpich: [5.0.1] }
          docfiles: [README.md, README_GPU.md, CONTRIBUTING.md]
          build_requires: [ cmake/4.4.0, git/2.54.0, lapack/3.12.1, hdf5/2.2.0, fftw/3.3.10, scalapack/2.2.3 ]
          runtime_deps: [hdf5/2.2.0]
          configure_args+:
            - -DQE_ENABLE_SCALAPACK:BOOL=ON
            - -DQE_ENABLE_MPI_GPU_AWARE:BOOL=ON
            - -DQE_GPU:STRING='openacc;cuda'
            - -DQE_GPU_ARCHS:STRING='sm_80'
            - -DBLAS_LIBRARIES=${LAPACK_LIBRARY_DIR}/libblas.so.3.12.0
            - -DLAPACK_LIBRARIES=${LAPACK_LIBRARY_DIR}/liblapack.so.3.12.0
            - -DCMAKE_C_COMPILER:STRING=${CC}
            - -DCMAKE_Fortran_COMPILER:STRING=${FC}
            - -DNVFORTRAN_CUDA_VERSION=12.9

    7.3.1:
      variants:
        - systems: [merlin-*, ra-*]
          group_deps:
            compiler: {gcc: [13.1.0]}
            mpi: {openmpi: [4.1.5_slurm]}
          relstage: unstable
          build_requires: [cmake/3.26.3, git/2.39.1, lapack/3.10.0, OpenBLAS/0.3.23, hdf5/1.13.1_slurm]
        - systems: [merlin-*, ra-*]
          group_deps:
            compiler: {nvhpc: [23.5_cuda_12.1]}
            mpi: {openmpi: [4.1.4_slurm]}
          relstage: unstable
          build_requires: [cmake/3.26.3, git/2.39.1]
          runtime_deps: [libfabric/1.18.0]
