---
# yamllint disable rule:line-length
format: 1
fftw:
  defaults:
    group: MPI
    overlay: base
    relstage: stable
    docfiles:
      - COPYRIGHT
      - COPYING
      - README
      - NEWS
    urls:
      - url: http://www.fftw.org/$P-${V_PKG}.tar.gz

  shasums:
    fftw-3.3.10.tar.gz: 56c932549852cddcfafdab3820b0200c7742675be92179e59e6215b340e26467
    fftw-3.3.8.tar.gz: 6113262f6e92c5bd474f2875fa1b01054c4ad5040f6b0da7c03c98821d9ae303
    fftw-3.3.9.tar.gz: bf2c7ce40b04ae811af714deb512510cc2c17b9ab9d6ddcf49fe4487eea7af3d

  versions:
    3.3.10:
      variants:
        - systems: [.*.merlin7.psi.ch]
          target_cpus: [x86_64]
          overlay: Alps
          group: Compiler
          group_deps:
            compiler:
              gcc: [13.4.0]
#           mpi:
#             openmpi: [5.0.8]
          build_requires: [cmake/3.20.5]
          configure_args:
#            - CC=${MPICC}
#            - CXX=${MPICXX}
#
# Multithreading. Enabling both is fines
            - --enable-threads
            - --enable-openmp
#
# MPI support
#           - --enable-mpi
#
# CPU optimizations
            - --enable-sse2
            - --enable-avx2
            - --with-pic
