#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

# :TODO: detect compiler
TOOLSET=intel-linux

BOOST_BUILD_PATH="${MODULE_BUILDDIR}"

pmodules.configure() {
	cd "${MODULE_SRCDIR}"
	"${MODULE_SRCDIR}"/bootstrap.sh \
		--prefix="${PREFIX}" \
		--with-libraries=all \
		--with-python-root="${PYTHON_PREFIX}" \
		-with-toolset=${TOOLSET} \
		|| exit 1
}

pmodules.build() {
	cd "${MODULE_SRCDIR}"
	./b2 \
		--build-type=minimal \
		--build-dir="${MODULE_BUILDDIR}" \
		--layout=system \
		--without-mpi \
		variant=release \
		link=static \
		threading=multi \
		stage
}

pmodules.install() {
	cd "${MODULE_SRCDIR}"
	./b2 \
		--build-type=minimal \
		--build-dir="${MODULE_BUILDDIR}" \
		--layout=system \
		--without-mpi \
		variant=release \
		link=static \
		threading=multi \
		install
}

pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies "${COMPILER}" 'Python'
pmodules.make_all

